language: java
sudo: false
dist: trusty
install: true
jdk:
- oraclejdk9
addons:
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.organization=cicti -Dsonar.login=$SONAR_TOKEN
cache:
  directories:
    - '$HOME/.sonar/cache'
    - '$HOME/.m2/repository'
deploy:
  provider: releases
  api_key: $GIT_APIKEY
  file: "/home/travis/build/Citos-CTI/Manager-Server/target/Citos-Server-1.0.1.jar"
  skip_cleanup: true
  on:
    tags: true
    branches:
    - master

