language: java
sudo: false
dist: trusty
install: true
jdk:
- oraclejdk8
addons:
  sonarcloud:
    branches:
      - master
    organization: "jebk"
    token:
      secure: "ixbZVr7IxaD9tPPxXKINHHwHXXZDFHTHRIhnj/FiLL9G2UuRx6SVtd3Bg9OVOl8u3h1nrx5KIKjcdw19mGm18b7Fj0WSnS7yPpaOgfATJrviU8LQMRv6iGxLGRVFCHc5jj3A8MAgTu1Xb1vgjk6vpto2U8gpYQxJ3Gt1k4Y+HsjbpArZApBXGcp/xKUxgldIDYDQaKp8ncALY3/KAk2Ga9PbvNASq9y4BLmFYHfmhWyEaW/0V13JZGVCDvalgXeqixXFaAPrP79wk3u1tAshExj2sgJ8XxkXCbwGXGEY4R+0DB49urDonK6UvQ4M5HBN4AMASsx74UVyHy/qdw+WOTcNmnEKFy+0gGfP6DS0nv9ZtTjtGgYIaZq+8jKHMu3LNjYj8DPaIyChnAPjdkN5D5Mny/PBi17V8yOwmU6sK2ACO/aVGhxacPLbemEuDtYsvzADDJS5uep6vRJzNTThg2JgLlJW56a5eFTO6B/0vtyuZXYYafjzhsRLXhhWBio5knqYVreKx2t60eqYwpL+K4BB+cDjPq9TO+WCJ19hRcvJxxf+RNd7qnfSsk1YJvbv5F/Yi1cKrmE9WCr/oDx5+9OfbO6Yyb9eS7cQTAKTG/5FLeyGuHt6QN8ulJ+uuxRpXL8nSPQG+iOrARsZF41uYHuw/qJmqt89KKpLbNhK1lw="
script:
  - mvn clean compile package sonar:sonar
cache:
  directories:
    - '$HOME/.sonar/cache'
    - '$HOME/.m2/repository'
deploy:
  provider: releases
  api_key:
    secure: "bQZBufd9gymEAHFPnHyPRGl0APQD5eCGonFImx1mZbaXuvG/FI0miL17SUmCV4Pvck4qNbkUAZwbNCirHqAiaCPJTWEZvXmF1PS8Vh0YEaO0mCbYNDVZlAIRJim/j7ZVcD1faOnQB6N50Q2XQibuP1kL9qf4XVTKcDn9IEmAqBAk1iQxegP7XnrnWy+dUX4ixBY0gzpWAnOw6BFgQIGdPUODQIGs9WrG37sqQGJaFp7SE7L/1g9zKGK3Mw80jLxWAz6QlSRucxBoSuEuqeMbtbTMr1hfNosvp9Vug/RAjgskH04GOGs71l3844vE/h12NHHcoOctHI2sFguBnWqA1Cf/IZbUtfA5aLYwqoODOT2SwwMiq6MmpTiW6hkoQ0efvrdWGcmeEpYqGmembnr5RDKk6f+PU2kdHfXPpKmk6Dgkuc8073oRRSyHf99ToypB/LsbAXEjuLm/P1fM4ETCCUsItHcWM8x19CIDh0KxORx/k3H21TteZu7nY5666Bioh1cg9hv26P+93tfInAZo8CMbEflT/5ZrjnAyRNsVTh9fwK375WAMDn6T1qVOKd3V4XEzw0KV2Zw4O4yKY3/XidIKnxTVUg/WgL91dUqtg7pbQJeuaKWwtR0hmyGUMb+MxomwrZkAr3/DCFFsBlkvWXod8YWqpmlK1fyFRmyQTCw="
  file: "$HOME/build/johannes5117/jtc/target/Citos-1.0.3.jar"
  skip_cleanup: true
  on:
    tags: true
    branches:
      - master

