language: java
sudo: false
dist: trusty
install: true
jdk:
- oraclejdk8
addons:
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.organization=cicti -Dsonar.login=$SONAR_TOKEN
cache:
  directories:
  - '$HOME/.sonar/cache'
  - '$HOME/.m2/repository'
deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file: "/home/travis/build/Citos-CTI/Server/target/Citos-Server-1.0.jar"
  skip_cleanup: true
  on:
    tags: true
    branches:
    - master